
management:
  server:
    port: 8080
  security:
    enabled: true

spring:
  datasource:
    spring:
      datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    #    url: jdbc:h2:file:/data/demo
    username: user
    password: user
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      fail-on-empty-beans: false
